### ISSUE TITLE
onvif NVT initialize: Exception: DioError [DioErrorType.other]: SocketException 

### ISSUE THREAD

**Issue by wmhseir3** [faithoflifedev/easy_onvif#1]
I am using one onvif nvt which is working with most nvt client software. However, when tried to use the sample codes as in the easy_onvif as followings (as in #1), the app yields the exception as in #2. My flutter doctor info are as in #3.  I further step into the codes to debug the causes and found it roots from #4 routine. Can you please look into the the issue and advise how to clear it next. Thanks.
1.
  _initialize() async {
    var onvif = Onvif(
        host: '192.168.1.101:8899',
        username: 'admin',
        password: 'password');
    //initiate connection
    await onvif.initialize();
    //get device info
    var deviceInfo = await onvif.deviceManagement.getDeviceInformation();
    Fimber.i('$TAG _initialize: deviceInfo.model = ${deviceInfo.model}');
    //get device profiles
    var profs = await onvif.media.getProfiles();
    profs.forEach((element) {
      Fimber.i('$TAG _initialize: profs = $element.name, $element.token');
    });
    var profileToken = profs[0].token;
    Fimber.i('$TAG _initialize: profileToken = $profileToken');
  }
2.
E/flutter (27781): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Exception: DioError [DioErrorType.other]: SocketException: OS Error: Connection timed out, errno = 110, address = 192.168.1.101, port = 44088
E/flutter (27781): #0      DioMixin.assureDioError (package:dio/src/dio_mixin.dart:819:20)
E/flutter (27781): #1      DioMixin._dispatchRequest (package:dio/src/dio_mixin.dart:678:13)
E/flutter (27781): <asynchronous suspension>
E/flutter (27781): #2      DioMixin.fetch.<anonymous closure>.<anonymous closure> (package:dio/src/dio_mixin.dart)
E/flutter (27781): <asynchronous suspension>
E/flutter (27781): 
E/flutter (27781): #0      Soap.send (package:easy_onvif/src/soap.dart:34:7)
E/flutter (27781): <asynchronous suspension>
E/flutter (27781): #1      Soap.retrieveEnvlope (package:easy_onvif/src/soap.dart:43:26)
E/flutter (27781): <asynchronous suspension>
E/flutter (27781): #2      DeviceManagement.getSystemDateAndTime (package:easy_onvif/src/deviceManagement.dart:145:22)
E/flutter (27781): <asynchronous suspension>
E/flutter (27781): #3      Onvif.initialize (package:easy_onvif/src/onvif.dart:33:22)
E/flutter (27781): <asynchronous suspension>
E/flutter (27781): #4      _MyHomePageState._initialize (package:testeasyonvif/main.dart:79:5)
E/flutter (27781): <asynchronous suspension>
3.
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19042.1110], locale zh-TW)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc1)
• Platform android-30, build-tools 30.0.0-rc1
• Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)
4.
  Future<SystemDateAndTime> getSystemDateAndTime() async {
    final envelope = await Soap.retrieveEnvlope(
        uri, SoapRequest.envelope(null, SoapRequest.systemDateAndTime()));

**Comment by faithoflifedev** [comment]
Hello @wmhseir3, it looks like there is a timeout connecting to your device. The library attempts to connect to "http://$host/onvif/device_service" where in your case host is "192.168.1.101:8899". You can try connecting with another tool like telnet to confirm connectivity between your computer and your Onvif device.

**Comment by wmhseir3** [comment]
I managed to find another onvif nvt to look into the initialize issue and found another clue which might be new to the issue or related I am not sure. The captured exception screen is as followings:
![easyonvif_getcapability_Exception](https://user-images.githubusercontent.com/55186251/135737031-7e0b7d26-f390-44af-909c-f35b11f6a3cf.jpg)
and the actual envelop received is as followings:
![nvt_envelope](https://user-images.githubusercontent.com/55186251/135737044-4c8d9911-846f-4c4f-bdf3-9c0ee003e16b.jpg)
From my understandings, the system.dart is missing the "Extension" Jsonkey, or else, which can be the root cause of the exception.
Am I right on this? 
I was then further realized that using those JsonSerializable related *.g.dart files which may be with object coding style preferences. However, it may cause troubles when facing a variety of brands of onvif nvts in the market responding with not expected envelops.

**Comment by faithoflifedev** [comment]
Hi @wmhseir3,

This looks like a new issue.  Without being able to see the Soap XML generated by your device, it's difficult for me to troubleshoot the issue.  However, I have made an adjustment to the code and published a new version of the library.  This version makes more of the "capabilities" response from the Onvif device optional.  So if the device responds with a missing section, it won't error out.  This may resolve your issue.  If not, we'll look at figuring out the easiest way to get the Soap XML response for your device.

**Comment by wmhseir3** [comment]
Hi, here is the mentioned xml for the capabilities from the tested nvt
[capabilities.txt](https://github.com/faithoflifedev/easy_onvif/files/7278409/capabilities.txt)
.
