### ISSUE TITLE
getPresets() failed

### ISSUE THREAD

**Issue by Pioxis** [faithoflifedev/easy_onvif#19]
Hello,

After call:

```Dart
var presets = await insertO.ptz.getPresets(profs[0].token, limit: 15);
```

I'm getting error:

```
flutter: ‼️ 14:14:47.675264 ERROR    UI Loggy - Onvif - ERROR:
DioError [DioErrorType.response]: Http status error [500]
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Exception: Error code: {Code: {Value: {$: env:Receiver}, Subcode: {Value: {$: ter:ActionNotSupported}, Subcode: {Value: {$: ter:InvalidOperation}}}}, Reason: {Text: {@xml:lang: en, $: Optional Action Not Implemented}}}
#0      Soap.send (package:easy_onvif/src/soap.dart:43:11)
<asynchronous suspension>
#1      Soap.retrieveEnvelope (package:easy_onvif/src/soap.dart:59:26)
<asynchronous suspension>
#2      Ptz.getPresets (package:easy_onvif/src/ptz.dart:173:22)
<asynchronous suspension>

```

**Comment by faithoflifedev** [comment]
Hello @Pioxis,

The errors returned from your device are "ActionNotSupported" and "InvalidOperation".  Most likely the device is not fully Onvif compliant.  Have you tried any other Onvif software with it, like (node-onvif)[https://github.com/GuilhermeC18/node-onvif].

If node-onvif shows the same error then the problem is with your device.  You can try checking for updated firmware for the device.
