### ISSUE TITLE
OnvifUtil.xmlToMap

### ISSUE THREAD

**Issue by Ali1Ammar** [faithoflifedev/easy_onvif#22]
i have the following bug and i could not found the correct what to solve
I try to get an information about NVR using this package 

```dart
mac@alimac camera_playground % onvif  probe
Unhandled exception:
Exception
#0      OnvifUtil.xmlToMap (package:easy_onvif/src/util/util.dart:20:30)
#1      new Envelope.fromXml (package:easy_onvif/src/model/envelope.dart:23:35)
#2      MulticastProbe.probe.<anonymous closure> (package:easy_onvif/src/multicast_probe.dart:37:31)
#3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#7      _StreamController._add (dart:async/stream_controller.dart:648:7)
#8      _StreamController.add (dart:async/stream_controller.dart:596:5)
#9      new _RawDatagramSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:2413:33)
#10     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#11     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#12     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#13     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
mac@alimac camera_playground % 
```

**Comment by faithoflifedev** [comment]
Hi @Ali1Ammar,

I believe v2.0.13+13 should fix the issue.  It looks like I had a problem with the SOAP request namespace.
