### ISSUE TITLE
Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by wmhseir3** [faithoflifedev/easy_onvif#4]
The 0.0.9 has further exception @var profs = await onvif.media.getProfiles(); line with the following logcats:
E/flutter (11010): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast
E/flutter (11010): #0      _$CodeFromJson (package:easy_onvif/model/code.g.dart:11:37)
E/flutter (11010): #1      new Code.fromJson (package:easy_onvif/model/code.dart:17:55)
E/flutter (11010): #2      _$CodeFromJson (package:easy_onvif/model/code.g.dart:11:12)
E/flutter (11010): #3      new Code.fromJson (package:easy_onvif/model/code.dart:17:55)
E/flutter (11010): #4      _$FaultFromJson (package:easy_onvif/model/fault.g.dart:10:12)
E/flutter (11010): #5      new Fault.fromJson (package:easy_onvif/model/fault.dart:32:56)
E/flutter (11010): #6      _$BodyFromJson (package:easy_onvif/model/body.g.dart:12:19)
E/flutter (11010): #7      new Body.fromJson (package:easy_onvif/model/body.dart:121:55)
E/flutter (11010): #8      _$EnvelopeFromJson (package:easy_onvif/model/envelope.g.dart:10:18)
E/flutter (11010): #9      new Envelope.fromJson (package:easy_onvif/model/envelope.dart:19:7)
E/flutter (11010): #10     Soap.send (package:easy_onvif/src/soap.dart:27:35)
E/flutter (11010): <asynchronous suspension>
E/flutter (11010): #11     Soap.retrieveEnvlope (package:easy_onvif/src/soap.dart:43:26)
E/flutter (11010): <asynchronous suspension>
E/flutter (11010): #12     Media.getProfiles (package:easy_onvif/src/media.dart:35:22)

and here is the soap response when pasing it:
[getProfiles.txt](https://github.com/faithoflifedev/easy_onvif/files/7333988/getProfiles.txt)

**Comment by hsalazarl** [comment]
Getting the same but at the `onvif.initialize()` method call. Debugging results in this SOAP response:

```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:xs="http://www.w3.org/2000/10/XMLSchema" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2">
<soap:Body>
<soap:Fault>
<soap:Code>
<soap:Value>soap:Sender</soap:Value><soap:Subcode>
<soap:Value>wsse:InvalidSecurity</soap:Value>
</soap:Subcode>
</soap:Code>
<soap:Reason>
<soap:Text xml:lang="en">An error was discovered processing the wsse:Security header.</soap:Text>
</soap:Reason>
<soap:Node>http://www.w3.org/2003/05/soap-envelope/node/ultimateReceiver</soap:Node>
<soap:Role>http://www.w3.org/2003/05/soap-envelope/role/ultimateReceiver</soap:Role>
</soap:Fault>
</soap:Body>
</soap:Envelope>

```
